config/routes.rb
Instagramclone::Application.routes.draw do
  
  devise_for :users
  get 'comments/new'

  root 'posts#index'
  resources :tags
  
  resources :posts do
    resources :comments
    resources :charges
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true
	# validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	#resizes file to match dimensions. Saves storage space.
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" },
		storage: :s3,
    bucket: 'Instagram-Bucket-MS',
    s3_credentials: {
      access_key_id: Rails.application.secrets.s3_access_key,
      secret_access_key: Rails.application.secrets.s3_secret_key
    }

    has_and_belongs_to_many :tags 
    has_many :comments
    belongs_to :user

    def tag_names
    	tags.map(&:name).join
    end

    def tag_names=(tag_names)
    	tag_names.split(' ').uniq.each do |tag_name|
        tag_name.prepend('#') unless tag_name[0] == '#'

        tag = Tag.find_or_create_by(name: tag_name.downcase)
        tags << tag
      end
    end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts

	def to_param
		name.delete('#')
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
		@post = Post.find params[:post_id]
	end

	def create
	  # Amount in cents
	  @amount = 500


	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Pickcha-Gram print',
	    :currency    => 'usd'
	  )

	  flash[:notice] = 'Thanks for the $5!'
	  redirect_to '/posts'

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@post = Post.find params[:post_id]
  	@comment = Comment.new
  end

  def create
  	@post = Post.find params[:post_id]
  	@post.comments.new params[:comment].permit(:content)

  	if @post.save
  		flash[:notice] = 'Thanks for your comment'
  		redirect_to '/posts'
  	else
  		render 'new'
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, only: [:new, :create, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		puts params
		@post = Post.new params[:post].permit(:description, :picture, :tag_names)
		@post.user = current_user
		if @post.save
			redirect_to '/posts'
		else
			render 'new'
		end
	end

def destroy
  @post = current_user.posts.find params[:id]
  @post.destroy

  flash[:notice] = 'Post successfully deleted.'
  redirect_to '/posts'
rescue ActiveRecord::RecordNotFound
  flash[:notice] = 'Error: This is not your post!'
  redirect_to '/posts'
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  	@tag = Tag.find_by(name: '#' + params[:id])
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/new.html.erb
<h2> You are about to buy a print of this for $5 </h2>

<%= render @post %>

<%= form_tag post_charges_path(@post) do %>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
	<%= f.label :content, 'Comment' %>
	<%= f.text_area :content %>

	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagramclone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='/'>Pikcha-Gram |</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class: 'navbar-brand' %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-brand' %>
          
        <% end %>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
</nav>
<div class='container'>
  <%= notice %>
  <%= alert %>
  
	<%= yield %>
</div>

</body>
</html>

app/views/posts/_post.html.erb
		<div class='col-md-4'>
			
			
			<%=image_tag post.picture.url(:medium)%>
			
			<h3><%= post.description %></h3>
			<p>
				<% post.tags.each do |tag| %>
					<%= link_to tag.name, tag_path(tag) %>
				<% end %>
			</p>

			<p>
				<%= pluralize post.comments.count, 'comment'%> 
			</p>

			<p>
				<%= link_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger' %>
				<%= link_to 'Add a comment', new_post_comment_path(post), class: 'btn btn-primary' %>
				<%= link_to 'Buy', new_post_charge_path(post), class: 'btn btn-success' %>
			</p>
			
		</div>

app/views/posts/index.html.erb
<div class='row'>
	<% if @posts.any? %>
		<%= render @posts %>
	<% else %>
		No posts yet.
	<% end%>

</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @post, html: { multipart: true } do |f| %>
	<%= f.label :description %>
	<%= f.text_area :description %>

  <%= f.label :tag_names, 'Tags' %>
  <%= f.text_field :tag_names %>

	<%= f.label :picture %>
	<%= f.file_field :picture %>

	<%= f.submit %>
<% end %>

app/views/tags/show.html.erb
<%= render @tag.posts %>